apiVersion: apps/v1
kind: Deployment
metadata:
  name: easytravel-www
  namespace: easytravel
spec:
  selector:
    matchLabels:
      app: easytravel
      tier: web
  replicas: 1
  template:
    metadata:
      labels:
        app: easytravel
        tier: web
      annotations:
        contact: "demo@dynatrace.com"
        priority: "high"
        tier: web
        app: easytravel
    spec:
      containers:
      - image: dynatrace/easytravel-nginx:2.0.0.3218
        name: easytravel-www
        envFrom:
        - configMapRef:
            name: easytravel-config
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: 80
        #     scheme: HTTP
        #   initialDelaySeconds: 5
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 80
        #     scheme: HTTP
        #   initialDelaySeconds: 120
        #   periodSeconds: 120
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: easytravel
    tier: web
  name: easytravel-www
  namespace: easytravel
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: easytravel
    tier: web
  type: LoadBalancer
