apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: easytravel
    tier: loadgen
  name: loadgen
  namespace: easytravel
spec:
  selector:
    matchLabels:
      app: easytravel
      tier: loadgen
  replicas: 1
  template:
    metadata:
      labels:
        app: easytravel
        tier: loadgen
      annotations:
        contact: "demo@dynatrace.com"
        priority: "low"
        tier: loadgen
        app: easytravel
    spec:
      containers:
      - image: dynatrace/easytravel-loadgen:2.0.0.3218
        name: loadgen
        envFrom:
        - configMapRef:
            easytravel-config
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
