#Example - Don't source control actual secrets
apiVersion: v1
kind: Secret
metadata:
  name: mongo-credentials
  namespace: easytravel
type: Opaque
data:
  ET_MONGO_AUTH_DB: "YWRtaW4K" #admin
  ET_DATABASE_USER: "ZXRBZG1pbgo=" #etAdmin
  ET_DATABASE_PASSWORD: "YWRtaW5hZG1pbgo=" #adminadmin